### PR TITLE
i don't like how it's capitalized for every word

### PR DESCRIPTION
**Pull request by 40j**
that looks fucking dumb

### CODE REVIEW

**Review by NahSahh — COMMENTED** [review]
Kurp likes them capitalised.

**Comment by Kurpp** [comment]
Hmm well @bbrooklyn @NahSahh thoughts? i dont hate it
old
new

**Comment by bbrooklyn** [comment]
I agree with @40j , I think this is an improvement.

**Comment by bbrooklyn** [comment]
Thoughts on this @NahSahh ?

**Comment by bbrooklyn** [comment]
Talking too long to reply, I'm merging :smile:

**Pull request merged**
